"""empty message

Revision ID: 8a9b12bb0fca
Revises: 
Create Date: 2017-03-13 02:22:17.778502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9b12bb0fca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ronda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiempo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiempo', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('passw', sa.String(length=40), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('integrante', sa.Integer(), nullable=True),
    sa.Column('tiempo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['integrante'], ['integrante.id'], ),
    sa.ForeignKeyConstraint(['tiempo'], ['tiempo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipo')
    op.drop_table('tiempo')
    op.drop_table('ronda')
    op.drop_table('integrante')
    # ### end Alembic commands ###
